### ISSUE TITLE
question about the 4-parameter logistic function in TOPIQ

### ISSUE THREAD

**Issue by cyclopssssss** [chaofengc/IQA-PyTorch#103]
Hi, thank you for such an excellent repository!
In your paper TOPIQ, you mentioned before calculating the PLCC, the scores need to go through a logistic func
![FJ_F7WO@QYHB~8@ C$2PV15](https://github.com/chaofengc/IQA-PyTorch/assets/50789512/8bcad34f-532a-4acd-a9bd-095d1006009b)
but i don't see any operations like this in the topiq_arch.py, how to deal with it?

**Comment by chaofengc** [comment]
Please see explanations in readme: 
https://github.com/chaofengc/IQA-PyTorch#performance-evaluation-protocol

In this repository, we did not use logistic correction because most deep learning methods already achieve high performance.
The paper just follow previous work for fair comparison.

If you want to use logistic correction, please refer to codes in https://github.com/chaofengc/IQA-PyTorch/blob/main/pyiqa/metrics/correlation_coefficient.py
