### ISSUE TITLE
Training on custom model-dataset combination

### ISSUE THREAD

**Issue by LorenzoAgnolucci** [chaofengc/IQA-PyTorch#134]
Hi @chaofengc!

Thanks for this awesome repo.

I need to train some metrics on datasets different from those corresponding to the pre-trained models. I have 2 questions:

1. How can I train metrics that do not have an associated options file? For example, I need to train HyperIQA on FLIVE, and I do not see suitable options.
2. How can I train a model on the whole training dataset instead of on a single split? My goal is to evaluate the cross dataset performance and, for example, in the options of DBCNN I see a ```split_index``` parameter. Is there a simple way to use the whole dataset?

Thanks in advance.

**Comment by chaofengc** [comment]
Thanks for your interest.

Here are answers to your question:
- For each dataset, we provide the example options in `options/default_dataset_opt.yml`. While for each different method, we provide some of the training settings in `options/train` folder. Example of HyperIQA is in `options/train/HyperNet/train_HyperNet.yml`, you may follow similar settings.
- To use the whole dataset for train/test instead of splits, you can simply remove the `split_file` option, where the `split_index` option will be ignored.

Hope these could help.

**Comment by LorenzoAgnolucci** [comment]
Thank you very much, now everything seems clear to me!
