### ISSUE TITLE
about the cuda and cudnn version 

### ISSUE THREAD

**Issue by wangwen-banban** [chaofengc/IQA-PyTorch#154]
![image](https://github.com/chaofengc/IQA-PyTorch/assets/115995795/5884da2d-9d9d-4e72-bd11-5ff08deab730)
i follow your steps of the installation, and it's not wrong with the dependencies. But I met this problem, show in the image. And i use it successfully before, but it doesn't work accidently.
the following is my cuda version
![image](https://github.com/chaofengc/IQA-PyTorch/assets/115995795/2239d17d-8079-46a2-8a36-252cfaf1bf31)

**Comment by chaofengc** [comment]
Here is the debug message from ChatGPT. It is likely because the pytorch is not corrected installed with CUDNN.

It seems you've uploaded an image of an error message from a Python program that's utilizing PyTorch and CUDA. The error appears to be related to a failed attempt to use a CNN (Convolutional Neural Network) within a PyTorch environment. The specific error message states:

```
RuntimeError: cuDNN: CHECKFAIL: SetAttribute CUDNN_ATTR_CONVOLUTION_COMP_MODE Failed, status: CUDNN_STATUS_NOT_SUPPORTED
```

This kind of error usually indicates an issue with the cuDNN installation or compatibility between cuDNN and the currently used GPU or CUDA version. Here are a few troubleshooting steps:

1. **Check CUDA and cuDNN Compatibility**: Make sure that the version of cuDNN is compatible with the installed CUDA version.
2. **Update or Reinstall cuDNN**: If there's a version mismatch or corruption, updating or reinstalling cuDNN may resolve the issue.
3. **Verify GPU Support**: Ensure that your GPU supports the version of CUDA and cuDNN you're trying to use.
4. **Check Environment Variables**: Environment variables related to CUDA and cuDNN (like `PATH`, `LD_LIBRARY_PATH`, and `CUDA_HOME`) should be correctly set.
5. **PyTorch Version**: Make sure the version of PyTorch you're using is compatible with your CUDA and cuDNN versions.

You might want to start by checking the versions and compatibility of CUDA, cuDNN, and PyTorch, and then proceed with the appropriate updates or configuration changes.

**Comment by wangwen-banban** [comment]
ok, thanks
