### ISSUE TITLE
PYIQA development question

### ISSUE THREAD

**Issue by snk4tr** [chaofengc/IQA-PyTorch#17]
Hey there.
First of all, I would like to acknowledge the contribution of this project to the field of Image Quality Assessment. It is important for people to get access to open source implementations of various metrics and measures.
I would like to ask you whether you considered to join the [piq](https://github.com/photosynthesis-team/piq) project. I see quite some code inheritance and, in some cases, even duplication that brings limited additional value. From the other hand, your contribution to the already well established library would be appreciated and could potentially bring more impact rather than development of a very similar product in parallel. If there are some reasons for not to join other than a wish to develop your own library, could you share them?

**Comment by chaofengc** [comment]
First and foremost, we greatly appreciate the contribution of piq. We make it clear in the comments as well as documents if codes are taken from other repositories, mainly piq and [IQA-optimization](https://github.com/dingkeyan93/IQA-optimization). 

Secondly, our project is mainly for research purpose of IQA with deep neural networks. As can be noticed, we spent lots of effort to clean dataset, build training pipelines and reproducing recent NR IQA methods based on deep learning. We collect implementations of several popular traditional metrics just for easy comparison. Our next focus will be reimplement and retraining latest IQA methods based on deep learning.

Since our projects have different targets in the next stage, we are sorry that we are not interested in joining piq.
