### ISSUE TITLE
FID score varies across different inferences

### ISSUE THREAD

**Issue by ryanxingql** [chaofengc/IQA-PyTorch#188]
Hi @chaofengc, thanks for your excellent work!

I’ve been trying to calculate the FID between two image datasets. However, I noticed that each time I run the inference, I get slightly different FID scores.

To address this, I initially set:

```python
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False
```

after [this line](https://github.com/chaofengc/IQA-PyTorch/blob/26406b6d8579b2088c070e944540376270872b42/pyiqa/models/inference_model.py#L78). With this change, the FID score remained consistent across different inference runs.

However, I observed that when running the inference on different servers, likely due to differences in cuDNN versions or other factors, the FID scores still varied slightly between servers. Given this, I decided to stop pursuing perfectly identical FID scores across different environments.

P.S. I’m comparing the ground-truth DIV2K dataset with its lossy version, and the FID scores are identical up to the first decimal place, with differences starting from the second decimal place. Additionally, the PSNR/SSIM/LPIPS scores are identical across all runs and servers, consistent up to four decimal places.

What is your opinion about it? Thank you.

**Comment by chaofengc** [comment]
Thank you for your feedback and kind words!

You're absolutely right that setting `torch.backends.cudnn.deterministic = True` and `torch.backends.cudnn.benchmark = False` is a good practice for ensuring reproducibility. I'll make sure to incorporate this change in future versions of the code.

Regarding the small differences in FID scores beyond the first decimal place, I think these minor variations shouldn't be a major concern. Since FID is not a highly precise metric, differences at this level are generally not meaningful, and focusing on decimals beyond the first may not offer valuable insights.

As for the better consistency you're seeing with PSNR, SSIM, and LPIPS, it might because these metrics are calculated with a default batch size of 1. This reduces parallelism, which in turn minimizes the influence of non-deterministic cuDNN operations. If you’d like to see if this improves consistency for FID as well, you can try setting the batch size to 1 using `fid_metric(dir1, dir2, batch_size=1)`. Let me know how it works out.

**Comment by ryanxingql** [comment]
Here's a polished version of your message:

Thank you for your valuable response! I experimented with setting the FID batch size to 1 (without enabling `torch.backends.cudnn.deterministic = True` or disabling `torch.backends.cudnn.benchmark = False`), and noticed that the variations only occur beyond the second decimal across different inferences and servers. It worked perfectly!

**Comment by ryanxingql** [comment]
Thank you for your valuable response! I experimented with setting the FID batch size to 1 (without enabling `torch.backends.cudnn.deterministic = True` or disabling `torch.backends.cudnn.benchmark = False`), and noticed that the variations only occur beyond the second decimal. It worked perfectly!

**Comment by chaofengc** [comment]
Glad to hear it works! 😄
