### ISSUE TITLE
Add UHD-IQA dataset

### ISSUE THREAD

**Issue by LorenzoAgnolucci** [chaofengc/IQA-PyTorch#199]
Hi @chaofengc!

We have recently released a high-resolution IQA dataset called UHD-IQA ([paper](https://arxiv.org/abs/2406.17472), [download](https://database.mmsp-kn.de/uhd-iqa-benchmark-database.html)) which was used for a [challenge](https://arxiv.org/abs/2409.16271) at the [AIM workshop](https://cvlai.net/aim/2024/) at ECCV 2024. I was wondering if the dataset could be added to the repo, as it represents a useful benchmark for testing IQA models on high-resolution images.

I'm fine with handling the dataset addition and then opening a PR, but first I want to be sure that I am aware of everything that needs to be done:
- I need to create a ```process_uhdiqa.py``` file under the ```scripts``` directory to generate the dataset info
- I do NOT need to create ```uhdiqa_dataset.py``` file under the ```pyiqa/data``` directory as the dataset has a standard structure that is compatible with the ```general_nr_dataset.py``` file
- I need to add some training configuration examples for some models under the ```options``` directory to show how to use the dataset for training
- I need to add the dataset to your repo on HuggingFace 
- I need to add the dataset to the [doc](https://github.com/chaofengc/IQA-PyTorch/blob/main/docs/Dataset_Preparation.md)
- I do NOT need to add the checkpoints of models trained on the dataset as I believe I do not have the permission to do that

Is this everything or is there something that I'm missing?

Thanks in advance.

**Comment by chaofengc** [comment]
Thank you so much for your valuable contribution. I am more than happy to assist you with adding the new UHD dataset.

It's great that you're willing to open a PR with all the necessary updates. Since the current documentation and project structure are still somewhat basic, new contributions require these extra effort. The existing to-do list is fairly comprehensive, and here are a few additional points that maybe helpful:

1. I appreciate that you're offering to provide the processing script. It’s also perfectly fine if you only include the final processed meta info. Note: you need to generate extra split file to help with training and testing.
2. Yes, the `general_nr_dataset.py` can handle CSV files in the following format:
   https://github.com/chaofengc/IQA-PyTorch/blob/b718f54f6e0948f139e7c53d315821a1361ced67/pyiqa/data/data_util.py#L19-L28 
   and returns a dictionary with `{'img': img_tensor, 'mos_label': mos_label_tensor, 'img_path': img_path}`. If you need the dataset class to return additional information, you may need to implement a custom dataset class.

For items 3, 4, and 5, your help would be greatly appreciated!

6. Regarding model checkpoints, you may need to add your own download link (just like the `arniqa` if you'd like to contribute one. I’m planning to move all checkpoints from GitHub releases to Hugging Face for faster downloads. You can also upload the `.pth` files to: https://huggingface.co/chaofengc/IQA-Toolbox-Weights

**Comment by LorenzoAgnolucci** [comment]
Thank you very much for your help! I think everything is clear now. I will start the implementation ASAP and I will open a PR when I'm done.

**Comment by chaofengc** [comment]
It is very nice of you to help! I plan to merge the split information into the meta `csv` file today, which will lead to some updates in the code. You may start working on the PR after that.

**Comment by chaofengc** [comment]
I have modified the code to support a meta CSV file containing split information. The split data is stored in the following format:

- Each sample is assigned a `train`, `val`, or `test` value corresponding to its split.
- The official split is saved in a column named `official_split`.
- Ten random splits are generated and stored using the format `ratio[split_ratio]_seed[seed number]_split[split index:02d]`. For example, for a split ratio of `train/val/test=8:0:2`, a seed number of 123, and the first split, the entry would be `ratio802_seed123_split01`.

The previous version using the split file is also preserved for compatibility purposes.

**Comment by LorenzoAgnolucci** [comment]
That's amazing, thank you very much!
