### ISSUE TITLE
entropy metric | out of memory

### ISSUE THREAD

**Issue by abcnorio** [chaofengc/IQA-PyTorch#203]
Hello,

may I ask while using the entropy metric on a dataset (call with folder) of >30k images of varying sizes, it broke right away with a cuda-OOM error of unallocated >80GB VRAM. Using the same metric on a single image does not bring any problems. Applying other metrices like hyperiqa or brisque on the same dataset works fine, ie. no errors whatsoever. The GPU is a 4090 with 24 GB VRAM.

Question: what has to be considered to apply the entropy metric on the whole dataset? Calling the script individually for each image and not for the whole folder will each time load the whole model which is a waste of time, right?

Thanks!

**Comment by chaofengc** [comment]
The issue is likely due to the large size of your image, which can cause an OOM error. To take full advantage of the GPU’s parallel processing power, the `entropy` metric tends to require large memory for large size inputs. 

As an alternative, you can use `--device cpu` when dealing with large images for the entropy metric.

**Comment by abcnorio** [comment]
Thanks, will check individually whether there is a file that is just too big.
