### ISSUE TITLE
Citation ［Urgent]

### ISSUE THREAD

**Issue by allanchan339** [chaofengc/IQA-PyTorch#207]
Hey you made a great contribution on IQA and I want to cite this toolbox in the paper. 

However, production team in IEEE TIP ask this question and require us to reply within 24 hrs. 

```
Please provide the organization location, organization name, and report no.
for Ref. [56]

```

Where 56 is the refenence of IQA toolbox, generated by zotero from bibtex.

Could anyone help on this issue as this act also enhance the exposure of this excellent tool.

**Comment by chaofengc** [comment]
Thank you very much for citing our work! Since this is an online tool rather than an organizational publication, we may not be able to provide the requested details. If these specifics are essential, please feel free to remove this citation.

Alternatively, if convenient, you may consider referencing our related publication in TIP:

```bib
@article{chen2024topiq,  
  author = {Chen, Chaofeng and Mo, Jiadi and Hou, Jingwen and Wu, Haoning and Liao, Liang and Sun, Wenxiu and Yan, Qiong and Lin, Weisi},  
  title = {TOPIQ: A Top-Down Approach From Semantics to Distortions for Image Quality Assessment},  
  journal = {IEEE Transactions on Image Processing},  
  year = {2024},  
  volume = {33},  
  pages = {2404-2418},  
  doi = {10.1109/TIP.2024.3378466}  
}
```

**Comment by allanchan339** [comment]
Thx for the prompt reply. I have forwarded the answer and issue link to TIP for consideration.
