### ISSUE TITLE
possibly link error 

### ISSUE THREAD

**Issue by JuliBaCSE** [chaofengc/IQA-PyTorch#32]
https://github.com/chaofengc/IQA-PyTorch/blob/1edd189f802dbb565678fd45bf65437e2bb5c257/options/train/DBCNN/train_DBCNN.yml#L17

I guess it should be like:    split_file: ./datasets/train_split_info/livechallenge_seed123.pkl

Another question regarding the pertained models. Where can I get them since the folder is not found '.experiments/pretrained_models...'

**Comment by chaofengc** [comment]
Please read the `Train -> Dataset Preparation` part in readme carefully, the download link for split as well as meta information files are provided. Also note that please read other training instructions carefully if you want to train your own model.

And also please download the dataset first before training the model. Due to permission issue, we cannot provide the download link of datasets. You may refer to this github repo for help: https://github.com/icbcbicc/IQA-Dataset

**Comment by JuliBaCSE** [comment]
Hey, 
Thanks a lot for your help. 
The thing I was mentioning is that there is a small link error since I guess the split file should be in train_split_info and not in Meta info as stated in the doc I guess

**Comment by chaofengc** [comment]
Yes, you may fix the path error by yourself. Currently, the training scripts are not fully tested for all datasets. I will fix them when I am free，maybe recently🤗.
