### ISSUE TITLE
yml files for MUSIQ 

### ISSUE THREAD

**Issue by zwx8981** [chaofengc/IQA-PyTorch#36]
Hi chaofeng, can you share the yml file for training MUSIQ ? Thank you!

**Comment by chaofengc** [comment]
Thanks for interest. Due to limited resources, we have no plan to retrain MUSIQ at present. Yet we provide the pretrained model of  MUSIQ on imagenet for your convenience. 

https://github.com/chaofengc/IQA-PyTorch/blob/3edd510c48c9fb5ef7ba71c4e0fb9ccf67287298/pyiqa/archs/musiq_arch.py#L27-L28

Besides, if you want to retrain MUSIQ, please make sure the data preprocess is correct during training:

https://github.com/chaofengc/IQA-PyTorch/blob/3edd510c48c9fb5ef7ba71c4e0fb9ccf67287298/pyiqa/archs/musiq_arch.py#L347-L350

The `get_multiscale_patches` function should be used in the dataloader during training.

Except for the above two points, the rest configurations in the `yml` file should be the same as other NR method.

Sorry that we are not able to provide ready-to-use training of MUSIQ right now. It would be nice if you could help to contribute retraining codes of MUSIQ to our repository. Thank you !

**Comment by zwx8981** [comment]
Thanks for the detailed replay!

**Comment by nicolasch96** [comment]
Hello, 

Thank you for the support, it is really helpful.

I have an extra question on this topic: is the SPAQ weights a good starting point for retraining? or is it better to part from the imagenet weights?

Thank you!

Nicolas

**Comment by chaofengc** [comment]
Thank you for interest ! According to the MUSIQ paper, the SPAQ weights are initialized with pretrained imagenet weights.

As for new dataset, I am not sure which is better. You may try both.
