### ISSUE TITLE
Training questions about musiq

### ISSUE THREAD

**Issue by HIT-Wang** [chaofengc/IQA-PyTorch#46]
Thanks to the author for providing such an excellent iqa model code. Can the author upload the yml file of musiq-spaq? Thanks to the author 🙏

**Comment by chaofengc** [comment]
Sorry that I currently have no time to write the codes and test the correctness. It should be not difficult to modify the files by yourself, changes should be made to the dataloader file and musiq_arch file. 
It is also welcomed if you can make contributions to our repository when you finished testing the correctness of musiq training. 
Otherwise, it will take some time for me to update it to the repo.

**Comment by HIT-Wang** [comment]
okay，thanks for your respond. I will try some tricks to achieve the effect in your pre-trained musiq model

**Comment by HIT-Wang** [comment]
> Sorry that I currently have no time to write the codes and test the correctness. It should be not difficult to modify the files by yourself, changes should be made to the dataloader file and musiq_arch file. It is also welcomed if you can make contributions to our repository when you finished testing the correctness of musiq training. Otherwise, it will take some time for me to update it to the repo.

okay，thanks for your respond. I will try some tricks to achieve the effect in your pre-trained musiq model
