### ISSUE TITLE
Cannot find WaDIQaM 

### ISSUE THREAD

**Issue by mansur007** [chaofengc/IQA-PyTorch#94]
Hello, thank you for such a great repository!

I see that [model cards](https://github.com/chaofengc/IQA-PyTorch/blob/main/docs/ModelCard.md) include WaDIQaM
But I don't see it in the output of `pyiqa.list_models()`

Where can I find it?

Thank you

**Comment by chaofengc** [comment]
Thanks for your interest!

The model is implemented at `pyiqa/archs/wadiqam_arch.py`, but there are not official pytorch weights for this method. Since the method is a little bit old and results are not impressive, I have no timetable to re-train this model at present, and would probably update it when I have time.

It would be great if you are interest in this method and could help to re-train the model with our codes, examples and instructions in the documents. Your contributions will be of great value to the community.

**Comment by chaofengc** [comment]
The pretrained models are now implemented, and can be used with latest code.
**Please note that the re-trained model used our setting and is different from original paper.**
